services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04
    environment:
      MSSQL_SA_PASSWORD: "LocalDev2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  sqlserver-data:
    driver: local